### ISSUE TITLE
Accessory not responding.

### ISSUE THREAD

**Issue by 5chm3gz** [apexad/homebridge-eufy-robovac#1]
[text-0B579462CFF3-1.txt](https://github.com/joshstrange/homebridge-eufy-robovac/files/3410587/text-0B579462CFF3-1.txt)
Config attached. 
Is IP the ip address grabbed using adb or the local IP as per my router?

Homebridge is showing the device in the app, but it is always showing no response, and the accessory is not responding. Sometimes the status is all off in red. Is this git still supported?

**Comment by ollyboon** [comment]
@5chm3gz You should use either the IP address OR the device ID. I've got mine running using the device id only. I do have response but have it turning off and returning to base after a few seconds. Let me know if you get any further.

**Comment by joshstrange** [comment]
@5chm3gz Sorry I missed your first message. Can you tell me what model of RoboVac you are using? I have a 30C (all I could test on). The IP is the one from your router (adb might show the same one? not sure, I grabbed mine from scanning my network). Like @ollyboon said you just need the deviceId+secret OR IP+secret. 

I prefer the deviceId+secret because it's more resilient if you robovac gets a new IP address (though static IP's setup on your router could solve this problem). 

@ollyboon If you open a new ticket I might be able to help. I'll be 100% honest, I rarely use this HomeKit skill other than to make it beep when it's lost somewhere because my robovac runs on a schedule 99.99% of the time. This was more of a proof-of-concept/homekit-all-the-things but I can try to help you.

**Comment by ollyboon** [comment]
@joshstrange fair enough! I've got the 15C. I've got it set up properly (can make it beep etc). I just having trouble with what I mentioned above. I can't do a schedule due to having to move rugs, cables etc.. So I was attempting to use your plugin to run a Siri shortcut daily to ask whether I want to vacuum or not. I'll open an Issue and can hopefully explain more. Thanks for your help!

**Comment by apexad** [comment]
Duplicate of #3 #8 #4 
This should now be fixed as well.  However, please note, it seems IP address is no longer supported by the Tuya API (used by this plugin).  Please switch to deviceId if you are using IP address.  I will update the plugin README and such to reflect this soon.

**Comment by tritter** [comment]
@apexad I think its back again... Using the latest release v2.1.1 and using deviceId only...

`
Found device bfd3dcff6f6480ad0bcm56 at 192.168.0.43
Connecting...
Connected!
Status Updated!
Status Updated!
Looking for device...
Looking for device...
Looking for device...
Looking for device...
Status Updated!
(node:8296) UnhandledPromiseRejectionWarning: Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Looking for device...
Looking for device...
(node:8296) UnhandledPromiseRejectionWarning: Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:8296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`

**Comment by nihirpatel** [comment]
Also getting the same issue using device ID..

`(node:1373) UnhandledPromiseRejectionWarning: Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /homebridge/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:1373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)`

The vacuum (15C) is powered on and on the charger.
